### ISSUE TITLE
Automate Terraform module releases to S3

### ISSUE THREAD

**Issue by blsmth** [HailLab/brim-tf-azure-module#9]
## Summary
Set up automated release process to publish this Terraform module to S3 when new version tags are pushed.

## Background
We need to distribute this Terraform module via S3 to allow teams to consume it as a module source. This will enable versioned releases and consistent deployment across projects.

### GitHub Actions Workflow
Create `.github/workflows/release.yml` based on the existing pattern:

```yaml
name: Release Module
on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create tarball
        run: |
          cd src && tar -czf "../brim-tf-azure-module-${GITHUB_REF_NAME}.tar.gz" \
             $(find . -type f \( \
               -name "*.tf" -o \
               -name "*.tfvars" -o \
               -name "README.md" \))

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::302263087543:role/s3-deploy-bucket-access-role
          aws-region: us-east-2

      - name: Upload to S3
        run: |
          aws s3 cp brim-tf-azure-module-${GITHUB_REF_NAME}.tar.gz s3://brim-tf-azure-module/
          aws s3 cp brim-tf-azure-module-${GITHUB_REF_NAME}.tar.gz s3://brim-tf-azure-module/brim-tf-azure-module-latest.tar.gz
```

## S3 Structure
The module will be available at:
- Versioned: `s3://brim-tf-azure-module/brim-tf-azure-module-v1.0.0.tar.gz`
- Latest: `s3://brim-tf-azure-module/brim-tf-azure-module-latest.tar.gz`

## Module Usage
Teams can reference the module using:
```hcl
module "brim_azure" {
  source = "s3::https://s3.us-east-2.amazonaws.com/brim-tf-azure-module/brim-tf-azure-module-v1.0.0.tar.gz"
  
  # Module variables
  resource_group_name = "my-rg"
  location           = "eastus"
  # ...
}
```

## Tasks
- [ ] Create `.github/workflows/release.yml` file
- [ ] Verify IAM role permissions for S3 uploads
- [ ] Create S3 bucket `brim-tf-azure-module` if it doesn't exist
- [ ] Test release process with a test tag
- [ ] Update README with module consumption instructions

## Notes
- Using OIDC authentication with AWS (no long-lived credentials)
- Includes all `.tf`, `.tfvars`, and `README.md` files from src directory
- Maintains both versioned and latest releases
- S3 bucket should have versioning enabled for rollback capability
